package deck

import "github.com/davidperjans/deckroyale/internal/types"

var CardDataByName = map[string]types.Card{
	"Archer Queen":     {Name: "Archer Queen", ElixirCost: 5},
	"Arrows":           {Name: "Arrows", ElixirCost: 3},
	"Baby Dragon":      {Name: "Baby Dragon", ElixirCost: 4},
	"Bandit":           {Name: "Bandit", ElixirCost: 3},
	"Barbarian Barrel": {Name: "Barbarian Barrel", ElixirCost: 2},
	"Barbarians":       {Name: "Barbarians", ElixirCost: 5},
	"Bats":             {Name: "Bats", ElixirCost: 2},
	"Battle Healer":    {Name: "Battle Healer", ElixirCost: 4},
	"Battle Ram":       {Name: "Battle Ram", ElixirCost: 4},
	"Bomb Tower":       {Name: "Bomb Tower", ElixirCost: 4},
	"Bomber":           {Name: "Bomber", ElixirCost: 2},
	"Bowler":           {Name: "Bowler", ElixirCost: 5},
	"Cannon":           {Name: "Cannon", ElixirCost: 3},
	"Cannon Cart":      {Name: "Cannon Cart", ElixirCost: 5},
	"Clone":            {Name: "Clone", ElixirCost: 3},
	"Dark Prince":      {Name: "Dark Prince", ElixirCost: 4},
	"Dart Goblin":      {Name: "Dart Goblin", ElixirCost: 3},
	"Earthquake":       {Name: "Earthquake", ElixirCost: 3},
	"Electro Dragon":   {Name: "Electro Dragon", ElixirCost: 5},
	"Electro Giant":    {Name: "Electro Giant", ElixirCost: 8},
	"Electro Spirit":   {Name: "Electro Spirit", ElixirCost: 1},
	"Electro Wizard":   {Name: "Electro Wizard", ElixirCost: 4},
	"Elite Barbarians": {Name: "Elite Barbarians", ElixirCost: 6},
	"Elixir Collector": {Name: "Elixir Collector", ElixirCost: 6},
	"Ebarbs":           {Name: "Elite Barbarians", ElixirCost: 6}, // Alias
	"Eagle Giant":      {Name: "Electro Giant", ElixirCost: 8},    // Alias
	"Elixir Golem":     {Name: "Elixir Golem", ElixirCost: 3},
	"Executioner":      {Name: "Executioner", ElixirCost: 5},
	"Fire Spirit":      {Name: "Fire Spirit", ElixirCost: 1},
	"Fireball":         {Name: "Fireball", ElixirCost: 4},
	"Fisherman":        {Name: "Fisherman", ElixirCost: 3},
	"Flying Machine":   {Name: "Flying Machine", ElixirCost: 4},
	"Freeze":           {Name: "Freeze", ElixirCost: 4},
	"Giant":            {Name: "Giant", ElixirCost: 5},
	"Giant Skeleton":   {Name: "Giant Skeleton", ElixirCost: 6},
	"Giant Snowball":   {Name: "Giant Snowball", ElixirCost: 2},
	"Goblin Barrel":    {Name: "Goblin Barrel", ElixirCost: 3},
	"Goblin Cage":      {Name: "Goblin Cage", ElixirCost: 4},
	"Goblin Drill":     {Name: "Goblin Drill", ElixirCost: 4},
	"Goblin Gang":      {Name: "Goblin Gang", ElixirCost: 3},
	"Goblin Giant":     {Name: "Goblin Giant", ElixirCost: 6},
	"Goblin Hut":       {Name: "Goblin Hut", ElixirCost: 4},
	"Goblin":           {Name: "Goblin", ElixirCost: 2},
	"Golden Knight":    {Name: "Golden Knight", ElixirCost: 4},
	"Golem":            {Name: "Golem", ElixirCost: 8},
	"Graveyard":        {Name: "Graveyard", ElixirCost: 5},
	"Guards":           {Name: "Guards", ElixirCost: 3},
	"Heal Spirit":      {Name: "Heal Spirit", ElixirCost: 1},
	"Hog Rider":        {Name: "Hog Rider", ElixirCost: 4},
	"Hunter":           {Name: "Hunter", ElixirCost: 4},
	"Ice Golem":        {Name: "Ice Golem", ElixirCost: 2},
	"Ice Spirit":       {Name: "Ice Spirit", ElixirCost: 1},
	"Ice Wizard":       {Name: "Ice Wizard", ElixirCost: 3},
	"Inferno Dragon":   {Name: "Inferno Dragon", ElixirCost: 4},
	"Inferno Tower":    {Name: "Inferno Tower", ElixirCost: 5},
	"Knight":           {Name: "Knight", ElixirCost: 3},
	"Lava Hound":       {Name: "Lava Hound", ElixirCost: 7},
	"Lightning":        {Name: "Lightning", ElixirCost: 6},
	"Lumberjack":       {Name: "Lumberjack", ElixirCost: 4},
	"Magic Archer":     {Name: "Magic Archer", ElixirCost: 4},
	"Mega Minion":      {Name: "Mega Minion", ElixirCost: 3},
	"Mega Knight":      {Name: "Mega Knight", ElixirCost: 7},
	"Miner":            {Name: "Miner", ElixirCost: 3},
	"Mini P.E.K.K.A":   {Name: "Mini P.E.K.K.A", ElixirCost: 4},
	"Minions":          {Name: "Minions", ElixirCost: 3},
	"Minion Horde":     {Name: "Minion Horde", ElixirCost: 5},
	"Mirror":           {Name: "Mirror", ElixirCost: 1}, // Variable, but 1 for base
	"Mortar":           {Name: "Mortar", ElixirCost: 4},
	"Mother Witch":     {Name: "Mother Witch", ElixirCost: 4},
	"Musketeer":        {Name: "Musketeer", ElixirCost: 4},
	"Night Witch":      {Name: "Night Witch", ElixirCost: 4},
	"P.E.K.K.A":        {Name: "P.E.K.K.A", ElixirCost: 7},
	"Phoenix":          {Name: "Phoenix", ElixirCost: 4},
	"Poison":           {Name: "Poison", ElixirCost: 4},
	"Prince":           {Name: "Prince", ElixirCost: 5},
	"Princess":         {Name: "Princess", ElixirCost: 3},
	"Rage":             {Name: "Rage", ElixirCost: 2},
	"Ram Rider":        {Name: "Ram Rider", ElixirCost: 5},
	"Rascals":          {Name: "Rascals", ElixirCost: 5},
	"Rocket":           {Name: "Rocket", ElixirCost: 6},
	"Royal Delivery":   {Name: "Royal Delivery", ElixirCost: 3},
	"Royal Ghost":      {Name: "Royal Ghost", ElixirCost: 3},
	"Royal Giant":      {Name: "Royal Giant", ElixirCost: 6},
	"Royal Hogs":       {Name: "Royal Hogs", ElixirCost: 5},
	"Royal Recruits":   {Name: "Royal Recruits", ElixirCost: 7},
	"Skeleton Army":    {Name: "Skeleton Army", ElixirCost: 3},
	"Skeleton Barrel":  {Name: "Skeleton Barrel", ElixirCost: 3},
	"Skeleton Dragons": {Name: "Skeleton Dragons", ElixirCost: 4},
	"Skeletons":        {Name: "Skeletons", ElixirCost: 1},
	"Sparky":           {Name: "Sparky", ElixirCost: 6},
	"Spear Goblins":    {Name: "Spear Goblins", ElixirCost: 2},
	"Tesla":            {Name: "Tesla", ElixirCost: 4},
	"The Log":          {Name: "The Log", ElixirCost: 2},
	"Three Musketeers": {Name: "Three Musketeers", ElixirCost: 9},
	"Tornado":          {Name: "Tornado", ElixirCost: 3},
	"Valkyrie":         {Name: "Valkyrie", ElixirCost: 4},
	"Wall Breakers":    {Name: "Wall Breakers", ElixirCost: 2},
	"Witch":            {Name: "Witch", ElixirCost: 5},
	"Wizard":           {Name: "Wizard", ElixirCost: 5},
	"X-Bow":            {Name: "X-Bow", ElixirCost: 6},
	"Zappies":          {Name: "Zappies", ElixirCost: 4},
	"Zap":              {Name: "Zap", ElixirCost: 2},
}
